-- ==========================================================
-- 02: BRONZE LAYER: RAW DATA INGESTION (Keep datatype as STRING for safety)
-- Project: Sydney Duty Free Sales Insights
-- Purpose: Ingesting 5 CSV files and building a relational model
-- ==========================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE SYDNEY_DF_WH;
USE DATABASE SYDNEY_DF_DB;
USE SCHEMA BRONZE;

-- Create Raw Tables (Schema matching my CSV files)
-- Keep datatype as STRING for safety

CREATE OR REPLACE TABLE SYDNEY_DF_DB.BRONZE.RAW_CUSTOMERS (
    CUSTOMER_ID STRING, 
    NATIONALITY STRING, 
    AGE_GROUP STRING
);

CREATE OR REPLACE TABLE SYDNEY_DF_DB.BRONZE.RAW_FLIGHTS (
    FLIGHT_NO STRING, 
    AIRLINE STRING, 
    DESTINATION STRING, 
    DEPARTURE_TIME STRING, 
    FLIGHT_STATUS STRING
);

CREATE OR REPLACE TABLE SYDNEY_DF_DB.BRONZE.RAW_EVENTS (
    EVENT_ID STRING, 
    EVENT_NAME STRING, 
    START_DATE STRING, 
    END_DATE STRING
);

CREATE OR REPLACE TABLE SYDNEY_DF_DB.BRONZE.RAW_PRODUCTS (
    PRODUCT_SKU STRING, 
    CATEGORY STRING, 
    ITEM STRING, 
    VARIANT STRING, 
    SELLING_PRICE FLOAT, 
    COST_PRICE FLOAT
);

CREATE OR REPLACE TABLE SYDNEY_DF_DB.BRONZE.RAW_TRANSACTIONS (
    TX_ID STRING, 
    LINE_NO NUMBER, 
    TX_TIME STRING, 
    CUSTOMER_ID STRING, 
    FLIGHT_NO STRING, 
    EVENT_ID STRING, 
    PRODUCT_SKU STRING, 
    QTY NUMBER, 
    UNIT_PRICE FLOAT, 
    NET_AMOUNT FLOAT, 
    DISC_AMOUNT FLOAT, 
    PROMO_ID STRING, 
    PAYMENT_METHOD STRING
);

-- Bulk Load from Stage to Bronze
COPY INTO SYDNEY_DF_DB.BRONZE.RAW_CUSTOMERS 
    FROM @SYDNEY_DF_DB.BRONZE.CSV_STAGE/customer_details.csv 
    FILE_FORMAT = (
        FORMAT_NAME = 'SYDNEY_DF_DB.BRONZE.CSV_FORMAT'
    );

COPY INTO SYDNEY_DF_DB.BRONZE.RAW_FLIGHTS 
    FROM @SYDNEY_DF_DB.BRONZE.CSV_STAGE/flight_schedules.csv 
    FILE_FORMAT = (
        FORMAT_NAME = 'SYDNEY_DF_DB.BRONZE.CSV_FORMAT'
    );

COPY INTO SYDNEY_DF_DB.BRONZE.RAW_EVENTS 
    FROM @SYDNEY_DF_DB.BRONZE.CSV_STAGE/holiday_events.csv 
    FILE_FORMAT = (
        FORMAT_NAME = 'SYDNEY_DF_DB.BRONZE.CSV_FORMAT'
    );

COPY INTO SYDNEY_DF_DB.BRONZE.RAW_PRODUCTS 
    FROM @SYDNEY_DF_DB.BRONZE.CSV_STAGE/product_master.csv 
    FILE_FORMAT = (
        FORMAT_NAME = 'SYDNEY_DF_DB.BRONZE.CSV_FORMAT'
    );

COPY INTO SYDNEY_DF_DB.BRONZE.RAW_TRANSACTIONS 
    FROM @SYDNEY_DF_DB.BRONZE.CSV_STAGE/transactions.csv 
    FILE_FORMAT = (
        FORMAT_NAME = 'SYDNEY_DF_DB.BRONZE.CSV_FORMAT'
    );

SELECT * FROM SYDNEY_DF_DB.BRONZE.RAW_TRANSACTIONS LIMIT 10;
